name: module_splash
description: Modulo de Splash - Aplicativo de notÃ­cias da Gran Cursos Online
module_authors:
  - Marcos Souza @devmrcs

version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lib_gran_core: 
    path: ../../../lib_gran_core

  lib_gran_design: 
    path: ../../../lib_gran_design

  lib_gran_auth: 
    path: ../../../lib_gran_auth

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.1.5
  mobx_codegen: 2.0.4

  flutter_lints: 1.0.4

  mocktail: 0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo-gran-news.png

scripts:
  app_run: flutter run -t lib/main.dart --flavor production

  build_apk: flutter build apk --split-per-abi -t lib/main.dart --flavor production
  build_bundle: flutter build appbundle -t lib/main.dart --flavor production

  mobx: flutter pub run build_runner build
  mobx_delete: flutter pub run build_runner build --delete-conflicting-outputs
  mobx_watch: flutter pub run build_runner watch
  mobx_clean: flutter pub run build_runner clean

  package_outdated: flutter pub outdated
  test_coverage: flutter test --coverage

  adb_restart_tcp: adb tcpip 5555
  adb_connect_tcp: adb connect 192.168.100.45:5555